version: '3.8'

networks:
  app_network:
    driver: bridge
    
services:
  db:
    container_name: courses_database
    image: postgres:latest
    environment:
      POSTGRES_USER: pgaccess
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: courses
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    container_name: backend_service
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    container_name: frontend_service
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app_network

volumes:
  postgres_data: