version: '3.8'

services:
  db:
    container_name: courses_database
    image: postgres:latest
    environment:
      POSTGRES_USER: pgaccess
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: courses
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: